export const blogCarouselData = [
    {
      category: 'Technology',
      title: 'Latest Tech Trends',
      image: '/technology.jpg',
      caption: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa dolorem sint placeat cum ducimus labore laboriosam quaerat? Placeat, quidem nisi!.....'
    },
    {
      category: 'Travel',
      title: 'Exploring New Destinations',
      image: '/travel.jpg',
      caption: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa dolorem sint placeat cum ducimus labore laboriosam quaerat? Placeat, quidem nisi!.....'
    },
    {
      category: 'Food',
      title: 'Delicious Recipes',
      image: '/food.jpg',
      caption: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa dolorem sint placeat cum ducimus labore laboriosam quaerat? Placeat, quidem nisi!.....'
    },
  ];

export const popularCategoriesData = [
    {
      name: 'Technology',
      link: '/categories/technology',
      imageSrc: '/technology.jpg', // Add an image source for the Technology category
    },
    {
      name: 'Travel',
      link: '/categories/travel',
      imageSrc: '/travel.jpg', // Add an image source for the Travel category
    },
    {
      name: 'Food',
      link: '/categories/food',
      imageSrc: '/food.jpg', // Add an image source for the Food category
    },
    {
      name: 'Fashion',
      link: '/categories/fashion',
      imageSrc: '/fashion.jpg', // Add an image source for the Food category
    },
    {
      name: 'Lifestyle',
      link: '/categories/lifestyle',
      imageSrc: '/lifestyle.jpg', // Add an image source for the Food category
    },
    {
      name: 'Health',
      link: '/categories/health',
      imageSrc: '/health.jpg', // Add an image source for the Food category
    },
];

export const trendingBlogsData = [
  {
    coverImage: 'fashion.jpg',
    tag: 'Tag 1',
    date: 'October 18, 2023',
    title: 'Blog Article 2 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 75,
    comments: 45,
    views: 600,
    authorImage: 'fashion.jpg',
    authorName: 'Author 2',
  },
  {
    coverImage: 'food.jpg',
    tag: 'Tag 2',
    date: 'October 16, 2023',
    title: 'Blog Article 3 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 120,
    comments: 60,
    views: 800,
    authorImage: 'food.jpg',
    authorName: 'Author 3',
  },
  {
    coverImage: 'lifestyle.jpg',
    tag: 'Tag 3',
    date: 'October 14, 2023',
    title: 'Blog Article 4 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 90,
    comments: 40,
    views: 700,
    authorImage: 'lifestyle.jpg',
    authorName: 'Author 4',
  },
  {
    coverImage: 'travel.jpg',
    tag: 'Tag 4',
    date: 'October 12, 2023',
    title: 'Blog Article 5 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: 'travel.jpg',
    authorName: 'Author 5',
  },
  {
    coverImage: 'technology.jpg',
    tag: 'Tag 5',
    date: 'October 12, 2023',
    title: 'Blog Article 5 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: 'technology.jpg',
    authorName: 'Author 5',
  },
  {
    coverImage: 'food.jpg',
    tag: 'Tag 6',
    date: 'October 12, 2023',
    title: 'Blog Article 5 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: 'food.jpg',
    authorName: 'Author 5',
  },
];

export const recentBlogsData = [
  {
    coverImage: 'fashion.jpg',
    tag: 'Tag 2',
    date: 'October 18, 2023',
    title: 'Blog Article 2 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 75,
    comments: 45,
    views: 600,
    authorImage: 'fashion.jpg',
    authorName: 'Author 2',
  },
  {
    coverImage: 'food.jpg',
    tag: 'Tag 3',
    date: 'October 16, 2023',
    title: 'Blog Article 3 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 120,
    comments: 60,
    views: 800,
    authorImage: 'food.jpg',
    authorName: 'Author 3',
  },
  {
    coverImage: 'lifestyle.jpg',
    tag: 'Tag 4',
    date: 'October 14, 2023',
    title: 'Blog Article 4 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 90,
    comments: 40,
    views: 700,
    authorImage: 'lifestyle.jpg',
    authorName: 'Author 4',
  },
  {
    coverImage: 'travel.jpg',
    tag: 'Tag 5',
    date: 'October 12, 2023',
    title: 'Blog Article 5 Title',
    caption: 'A short caption or excerpt from the article.',
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: 'travel.jpg',
    authorName: 'Author 5',
  },
];


export const allBlogCategories = [
  { name: "Lifestyle" },
  { name: "Travel" },
  { name: "Food and Cooking" },
  { name: "Fashion and Style" },
  { name: "Technology" },
  { name: "Health and Wellness" },
  { name: "Parenting and Family" },
  { name: "Finance and Personal Finance" },
  { name: "DIY and Home Improvement" },
  { name: "Education and Teaching" },
  { name: "Business and Entrepreneurship" },
  { name: "Entertainment and Pop Culture" },
  { name: "Gaming" },
  { name: "Books and Literature" },
  { name: "Environment and Sustainability" },
  { name: "Politics and News" },
  { name: "Sports and Athletics" },
  { name: "Science and Technology" },
  { name: "Personal Development and Self-Improvement" },
  { name: "Religion and Spirituality" },
  { name: "Photography and Visual Arts" },
  { name: "Crafts and Hobbies" },
  { name: "Music and Music Industry" },
  { name: "Pets and Animals" },
  { name: "History and Historical Events" },
  { name: "Motivation and Inspiration" },
  { name: "Gardening and Landscaping" },
  { name: "Travel Tips and Hacks" },
  { name: "Culinary and Gourmet" },
  { name: "Interior Design and Decor" },
  { name: "Education Technology (EdTech)" },
  { name: "Startups and Innovation" },
  { name: "Celebrity and Entertainment News" },
  { name: "Video Games and Gaming Industry" },
  { name: "Poetry and Creative Writing" },
  { name: "Climate Change and Environmental Activism" },
  { name: "Global and Local Politics" },
  { name: "Mental Health and Psychology" },
  { name: "Travel Adventures and Exploration" },
  { name: "Sports Analysis and Commentary" },
  { name: "Astronomy and Space Exploration" },
  { name: "Time Management and Productivity" },
  { name: "Yoga and Mindfulness" },
  { name: "Faith and Religious Philosophy" },
  { name: "Street Photography and Urban Art" },
  { name: "Collectibles and Antiques" },
  { name: "Indie Music and Bands" },
  { name: "Animal Rescue and Adoption" },
  { name: "Medieval History and Renaissance" },
  { name: "Life Hacks and Efficiency Tips" },
];
