export const blogCarouselData = [
  {
    category: "Technology",
    title: "Latest Tech Trends",
    image: "/technology.jpg",
    caption:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa dolorem sint placeat cum ducimus labore laboriosam quaerat? Placeat, quidem nisi!.....",
  },
  {
    category: "Travel",
    title: "Exploring New Destinations",
    image: "/travel.jpg",
    caption:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa dolorem sint placeat cum ducimus labore laboriosam quaerat? Placeat, quidem nisi!.....",
  },
  {
    category: "Food",
    title: "Delicious Recipes",
    image: "/food.jpg",
    caption:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa dolorem sint placeat cum ducimus labore laboriosam quaerat? Placeat, quidem nisi!.....",
  },
];

export const popularCategoriesData = [
  {
    name: "Technology",
    link: "/categories/technology",
    imageSrc: "/technology.jpg", // Add an image source for the Technology category
  },
  {
    name: "Travel",
    link: "/categories/travel",
    imageSrc: "/travel.jpg", // Add an image source for the Travel category
  },
  {
    name: "Food",
    link: "/categories/food",
    imageSrc: "/food.jpg", // Add an image source for the Food category
  },
  {
    name: "Fashion",
    link: "/categories/fashion",
    imageSrc: "/fashion.jpg", // Add an image source for the Food category
  },
  {
    name: "Lifestyle",
    link: "/categories/lifestyle",
    imageSrc: "/lifestyle.jpg", // Add an image source for the Food category
  },
  {
    name: "Health",
    link: "/categories/health",
    imageSrc: "/health.jpg", // Add an image source for the Food category
  },
];

export const trendingBlogsData = [
  {
    coverImage: "fashion.jpg",
    tag: "Tag 1",
    date: "October 18, 2023",
    title: "Blog Article 2 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 75,
    comments: 45,
    views: 600,
    authorImage: "fashion.jpg",
    authorName: "Author 2",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 2",
    date: "October 16, 2023",
    title: "Blog Article 3 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 120,
    comments: 60,
    views: 800,
    authorImage: "food.jpg",
    authorName: "Author 3",
  },
  {
    coverImage: "lifestyle.jpg",
    tag: "Tag 3",
    date: "October 14, 2023",
    title: "Blog Article 4 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 90,
    comments: 40,
    views: 700,
    authorImage: "lifestyle.jpg",
    authorName: "Author 4",
  },
  {
    coverImage: "travel.jpg",
    tag: "Tag 4",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "travel.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "technology.jpg",
    tag: "Tag 5",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "technology.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 6",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "food.jpg",
    authorName: "Author 5",
  },
];

export const recentBlogsData = [
  {
    coverImage: "fashion.jpg",
    tag: "Tag 2",
    date: "October 18, 2023",
    title: "Blog Article 2 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 75,
    comments: 45,
    views: 600,
    authorImage: "fashion.jpg",
    authorName: "Author 2",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 3",
    date: "October 16, 2023",
    title: "Blog Article 3 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 120,
    comments: 60,
    views: 800,
    authorImage: "food.jpg",
    authorName: "Author 3",
  },
  {
    coverImage: "lifestyle.jpg",
    tag: "Tag 4",
    date: "October 14, 2023",
    title: "Blog Article 4 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 90,
    comments: 40,
    views: 700,
    authorImage: "lifestyle.jpg",
    authorName: "Author 4",
  },
  {
    coverImage: "travel.jpg",
    tag: "Tag 5",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "travel.jpg",
    authorName: "Author 5",
  },
];

export const blogList = [
  {
    coverImage: "fashion.jpg",
    tag: "Tag 1",
    date: "October 18, 2023",
    title: "Blog Article 2 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 75,
    comments: 45,
    views: 600,
    authorImage: "fashion.jpg",
    authorName: "Author 2",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 2",
    date: "October 16, 2023",
    title: "Blog Article 3 Title",
    caption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus vitae ratione quisquam amet beatae repellat earum laudantium inventore voluptates sit ut in ab.",
    likes: 120,
    comments: 60,
    views: 800,
    authorImage: "food.jpg",
    authorName: "Author 3",
  },
  {
    coverImage: "lifestyle.jpg",
    tag: "Tag 3",
    date: "October 14, 2023",
    title: "Blog Article 4 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 90,
    comments: 40,
    views: 700,
    authorImage: "lifestyle.jpg",
    authorName: "Author 4",
  },
  {
    coverImage: "travel.jpg",
    tag: "Tag 4",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "travel.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "technology.jpg",
    tag: "Tag 5",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "technology.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 6",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "food.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 7",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "food.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 8",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "food.jpg",
    authorName: "Author 5",
  },
  {
    coverImage: "food.jpg",
    tag: "Tag 9",
    date: "October 12, 2023",
    title: "Blog Article 5 Title",
    caption: "A short caption or excerpt from the article.",
    likes: 150,
    comments: 70,
    views: 1000,
    authorImage: "food.jpg",
    authorName: "Author 5",
  },
];

export const minifiedPostData = [
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
  {
    authorImage: "travel.jpg",
    authorName: "Author",
    title: "Blog Title",
  },
];

export const allBlogCategories = [
  { name: "Lifestyle", posts: 20 },
  { name: "Travel", posts: 50 },
  { name: "Food", posts: 30 },
  { name: "Fashion", posts: 80 },
  { name: "Technology", posts: 40 },
  { name: "Health", posts: 20 },
  { name: "Parenting", posts: 70 },
  { name: "Finance", posts: 30 },
  { name: "DIY", posts: 67 },
  { name: "Education", posts: 80 },
  { name: "Business", posts: 40 },
  { name: "Entertainment", posts: 20 },
  { name: "Gaming", posts: 30 },
  { name: "Literature", posts: 60 },
  { name: "Environment", posts: 10 },
  { name: "Politics", posts: 15 },
  { name: "Sports", posts: 18 },
  { name: "Personal Development", posts: 10 },
  { name: "Religion", posts: 60 },
  { name: "Photography", posts: 45 },
  { name: "Crafts and Hobbies", posts: 30 },
  { name: "Music", posts: 20 },
  { name: "Animals", posts: 20 },
  { name: "History", posts: 40 },
  { name: "Motivation and Inspiration", posts: 10 },
  { name: "Gardening and Landscaping", posts: 30 },
  { name: "Interior Design", posts: 20 },
  { name: "Startups and Innovation", posts: 16 },
  { name: "Poetry and Creative Writing", posts: 10 },
  { name: "Psychology", posts: 45 },
  { name: "Space", posts: 18 },
  { name: "Productivity", posts: 29 },
  { name: "Yoga and Mindfulness", posts: 18 },
];
